# The Desicion Model of Real Estate Buyers and Sellers

#### Keywords

real estate, house, apartment, city, population, house price, community, price, market, interest rate

## A beginning.

The city of Vancouver introduced a foreign buyer tax to the real estate market, 15% of the property tax, if the buyers are not residence in the city. The tax affected the markted immediately with one month, however, after one year, now the market heated up again. The policy is considered as a temporary solution or even a possible failure. With high 15% tax, why the market is still hot? It is a big question mark for the whole city. 

People are puzzled: 
who are these foreign buyers? 
Who else are buying properties? 
Who are selling properties? 
Where are buyers and sellers are moving from and moving to? 
Are there any particular trend in certain communities? 
Is there any co-relationship between public investment and private investment with population movements? 
Will people leave house market when the interest rate go higher? 

These are the puzzles I try to reveal in this real estate market analysis. I would like to explore the population profile of the people in the real estate market, the community changes, and the city budget planning and enterprise developments in certain area, as well as the economic factors to find out how the real estate market moves, including the supplying side and also the demanding side. 

## A middle.
From a daily experience, I can see several demand scenarios for buying or selling properties, for example:
retired people looking for down-sized the apartment for easy management, 
newly wed couple looking for first home, 
new comer looking for first home to settling down, 
investor looking for profit, 
children's parents looking for better school zone. 

All of these demands are originated from people's social profiles change, for example, aging, marriage, immigrant status, employment status, rich or poor. 

Meanwhile, the city budge planning and also the enterprise investment are largely shaping the building constructions and public transportations movement. Where people work largely affects where people dine and stay in the night. The housing policy(including the social affordable housing and rental restrictions), on the other hand, will affect the supply level of the private building number. 

From policy side, for example, the immigrant policy, is one of the key factor of the potencial buyer pool indicator. The gathering spot of each nation, Chinese area, Korean area, Indian area, may be affeced by the immigrant policy a lot more than other area.

The geographic location may also be a key factor of the market, or at least, has differentiating influence of the buyers profiles. Downtown and quiet communities,  Waterview area and inland area may have different trends in the housing market. 

When I have the factors of deep population profile, city development,  as well as geographic locations for the housing market, I can perform an throughout analysis on these factors together with the changes of the housing market for certain period and certain area. 

The reason I mention the period validty here, is the interest rate and mortgage policy are the key factors from my general observation from news and report from the bank. As the intesest and the mortgage policy are various in the different time period, I will also add the time factor in my analysis. From what I observe, the interest rate is impacting the housing market, however, as it is very hard to predict, to make the setup of the model more practical, I would do the history data analysis first, and make intereste rate as a custom parameter, so user can simulate the housing market status using a custom interest rate.

My analysis will begin with an EDA report and follow by detail analysis for each factors.

## An end.
I hope the reveal of the correlationship between the housing demand with the population profile, city development plan, location, and policy change factors (or even with interest rate, economic environment)will help people to think more comprehensively towards housing market.And I hope the model I build will help the buyer or seller find a better timing for the transaction. 


