# More Interest, Lower House Price? {#slug-two}

#### Keywords
real estate, interest, house price, behavioral psychology, the housing bubble 

## The Puzzle
It’s true that when interest rates increase, the cost of borrowing becomes more expensive. 
The availability of capital and the demand for investment is also affected. 

However, over the past thirty years, increases in Canadian mortgage rates have not tended to trigger a decrease in houses prices. In fact, more often than not the reverse is true. the average five-year residential mortgage lending rate (from Statistics Canada) and compared it to the average selling price of a Canadian home (provided in a report by the Canadian Real Estate Association), on a month-by-month basis from January 1980, up to June 2010. Over this period, totaling 365 months, there were 156 instances where the five-year residential mortgage rate increased over the prior month, and in 97 of these cases, house prices increased two months later. Is the higher interest rate as a good sign of better economy?

#see the chart of interest rate/avg house price between 1980 - 2010:
https://beta.theglobeandmail.com/globe-investor/personal-finance/housing-price-calcualtor-how-would-a-correction-affect-your-selling-price/article18079370/?ref=http://www.theglobeandmail.com&


## The Thoughts

While it certainly is true that higher rates increase borrowing costs, but the increasing of interest rate also happens in periods with rising incomes, higher levels of employment and increasing consumer confidence. I want to take this chance to explore the relationship among the economy, interest rate, and the house price.


Additionally, I also want to introduce the behavioral psychology in the study. One of the assumptions here, people may become insensitive to the changes when time goes, in another word, the memory and forgetting may also be one of the numerous factors of the endurance of higher house price during the interest rate change process. In the analysis, I want to know if there are cyclical fluctuations along the interest rate change. 

## The Goal
The governments are using the interest rate much more frequently now as an important tool to drive the economy. For the housing industry heavily weighted cities like Vancouver, the increase or the decrease of the interest rate may or may not be the only key influencer of the house price. I want to use the analysis for the correlation to reveal the interrelation of the tool and the house price and provide the government some useful consultation suggestion for the economic policy. 
